### ISSUE TITLE
Strip hidden lines from code blocks

### ISSUE THREAD

**Issue by jonhoo** [livioribeiro/cargo-readme#8]
I just publish a library with a bunch of code examples in the crate-level docs. These docs use a really neat feature of the Rust documentation code blocks, namely that `#` can be used to hide lines from the output example code. To quote the [book](https://doc.rust-lang.org/book/documentation.html#documentation-as-tests):

> You can add lines that start with #, and they will be hidden from the output, but will be used when compiling your code. You can use this to your advantage. In this case, documentation comments need to apply to some kind of function, so if I want to show you just a documentation comment, I need to add a little function definition below it. At the same time, it's only there to satisfy the compiler, so hiding it makes the example more clear. You can use this technique to explain longer examples in detail, while still preserving the testability of your documentation.

Unfortunately, `cargo-readme` doesn't support this at the moment, leading to some added noise in the extracted code segments: https://github.com/jonhoo/fantoccini#examples. It's not too bad for that particular library since I'm not hiding too many lines, but it can quickly distract from the main points of the example, so it'd be really neat if `cargo-readme` could also support hiding these lines!

**Comment by livioribeiro** [comment]
`cargo-readme` actually removes hidden lines from the output, but in your library you have:

```rust
//! ```rust,no_run
//! # use fantoccini::Client;
```
The `//! ```rust,no_run` part is what is confusing `cargo-readme`, since it does not recognize the code block as rust code and treats it as if is it was another language.

In rust doc, you don't need to specify a block of code to be rust code, because rust is the default, just change it to:

```rust
//! ```no_run
```

and it will work.

Thanks for opening this issue and good rusting.

**Comment by jonhoo** [comment]
Perfect, thanks!
